config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from process_history.views import HomePageView

# Определение маршрутов (URL) для проекта
urlpatterns = [
    # URL для административной панели
    path('admin/', admin.site.urls),

    # Главная страница, обрабатываемая представлением HomePageView
    path('', HomePageView.as_view(), name='home'),

    # Подключение маршрутов приложения пользователей
    path('users/', include('users.urls', namespace='users')),

    # Подключение маршрутов приложения истории процессов
    path('process_history/', include('process_history.urls', namespace='process_history')),

    # Подключение маршрутов приложения назначения смен
    path('shift_assignment/', include('shift_assignment.urls', namespace='shift_assignment')),
]

# Если проект находится в режиме отладки (DEBUG), добавляем обработку статических файлов
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

process_history/urls.py
from django.urls import path
from .views import HomePageView, SaveProcessHistoryView, HistoryProcessCreateView

# Указываем пространство имен для приложения process_history
app_name = 'process_history'

urlpatterns = [
    # URL для создания новой записи истории процесса по первичному ключу (pk)
    path('create/<int:pk>/', HistoryProcessCreateView.as_view(), name='history_process_create'),

    # URL для главной страницы приложения
    path('', HomePageView.as_view(), name='home'),

    # URL для сохранения истории процесса, связанного с заданием (assignment_id)
    path('save_process_history/<int:assignment_id>/', SaveProcessHistoryView.as_view(), name='save_process_history'),
]

shift_assignment/urls.py
from django.urls import path
from .views import (
    ShiftAssignmentUpdateView,
    ShiftAssignmentDeleteView,
    ShiftAssignmentDetailView,
    UploadShiftAssignmentView,
    CompletedShiftAssignmentView,
    CompletedShiftAssignmentUpdateView,
    DeleteCompletedShiftView
)

# Указываем пространство имен для приложения shift_assignment
app_name = 'shift_assignment'  # Убедитесь, что это указано

urlpatterns = [
    # URL для загрузки нового задания
    path('upload/', UploadShiftAssignmentView.as_view(), name='upload_shift_assignment'),

    # URL для удаления задания по его первичному ключу (pk)
    path('shift_assignment/<int:pk>/delete/', ShiftAssignmentDeleteView.as_view(), name='delete_shift'),

    # URL для просмотра завершенного задания по его первичному ключу (pk)
    path('completed/<int:pk>/', CompletedShiftAssignmentView.as_view(), name='completed_shift_assignment'),

    # URL для просмотра деталей задания по его первичному ключу (pk)
    path('detail/<int:pk>/', ShiftAssignmentDetailView.as_view(), name='shift_assignment_detail'),

    # URL для обновления задания по его первичному ключу (pk)
    path('shift_assignment/<int:pk>/update/', ShiftAssignmentUpdateView.as_view(), name='update_shift'),

    # URL для обновления завершенного задания по его первичному ключу (pk)
    path('completed_shift_assignment/<int:pk>/update/', CompletedShiftAssignmentUpdateView.as_view(),
         name='completed_shift_assignment_update'),  # Новый маршрут

    # URL для удаления завершенного задания по его идентификатору (id)
    path('delete_completed_shift/<int:id>/', DeleteCompletedShiftView.as_view(), name='delete_completed_shift'),
]

users/urls.py
from django.urls import path
from .views import UserRegisterView, UserLoginView, UserLogoutView, UserProfileView, UserListView, UserUpdateView

app_name = 'users'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='user_register'),  # Регистрация
    path('login/', UserLoginView.as_view(), name='login_user'),  # Вход
    path('logout/', UserLogoutView.as_view(), name='logout'),  # Выход
    path('update/<int:pk>/', UserUpdateView.as_view(), name='update_user'),  # Обновление пользователя
    path('profile/<int:pk>/', UserProfileView.as_view(), name='user_profile'),  # Профиль пользователя
    path('users/', UserListView.as_view(), name='user_list'),  # Список пользователей
]

shift_assignment/forms.py
from django import forms
from django.core.exceptions import ValidationError

from users.forms import StyleFormMixin
from shift_assignment.models import ShiftAssignment, CompletedShiftAssignment


class ShiftAssignmentForm(StyleFormMixin, forms.ModelForm):
    """
    Форма для создания или редактирования сменного задания.

    Эта форма используется для ввода данных о сменном задании, включая
    номер партии, наименование операции, количество, оператора и идентификатор машины.
    """

    class Meta:
        model = ShiftAssignment  # Модель, с которой работает форма
        fields = ['batch_number', 'operation_name', 'quantity', 'operator', 'part_id', 'machine_id']


class CompletedShiftAssignmentForm(StyleFormMixin, forms.ModelForm):
    """
    Форма для создания или редактирования завершенного сменного задания.

    Эта форма используется для ввода данных о завершенном сменном задании,
    включая количество брака и причину остановки.
    """

    # Поле для ввода количества брака (необязательное)
    defect_quantity = forms.IntegerField(required=False, label='Количество брака', initial=0)

    # Поле для выбора причины остановки процесса
    stop_reason = forms.ChoiceField(
        choices=[
            ('Работа в нормальном режиме', 'Работа в нормальном режиме'),
            ('СлНал', 'СлНал'),
            ('ТОиР', 'ТОиР'),
            ('Прочее', 'Прочее'),
        ],
        label='Причина остановки'
    )

    class Meta:
        model = CompletedShiftAssignment  # Модель, с которой работает форма
        fields = [
            # 'date',  # Если нужно добавить поле даты, раскомментируйте
            'operator',
            'operation_name',
            'machine_id',
            'part_id',
            'batch_number',
            'quantity',
            'defect_quantity',
            'stop_reason'
        ]
        widgets = {
            # Кастомизация виджетов для полей формы
            'date': forms.DateInput(attrs={'type': 'date'}),
            'quantity': forms.NumberInput(attrs={'min': 1, 'placeholder': 'Введите количество'}),
            # Добавьте другие кастомные виджеты по необходимости
        }

    def clean_quantity(self):
        """
        Валидация поля quantity.

        Проверяет, что количество больше нуля. Если значение некорректно,
        выбрасывает ValidationError.
        """
        quantity = self.cleaned_data.get('quantity')

        if quantity is not None and quantity <= 0:
            raise ValidationError("Количество должно быть больше нуля.")

        return quantity

shift_assignment/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView, UpdateView, DeleteView
from .forms import ShiftAssignmentForm, CompletedShiftAssignmentForm
from .models import ShiftAssignment, CompletedShiftAssignment

import pandas as pd
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.http import JsonResponse


class UploadShiftAssignmentView(LoginRequiredMixin, View):
    """
    Представление для загрузки сменных заданий из Excel файла.

    Это представление обрабатывает загрузку файла и сохранение данных в базу данных.
    """

    template_name = 'shift_assignment/upload_shift_assignment.html'

    def get(self, request):
        """Обрабатывает GET запрос для отображения формы загрузки."""
        return render(request, self.template_name)

    def post(self, request):
        """Обрабатывает POST запрос для загрузки файла с данными."""
        if request.method == 'POST' and 'file' in request.FILES:
            file = request.FILES['file']
            try:
                # Проверка формата файла
                if not file.name.endswith(('.xls', '.xlsx')):
                    return JsonResponse({'status': 'error', 'message': 'Неподдерживаемый формат файла.'})

                # Парсинг Excel файла
                df = pd.read_excel(file)

                # Проверка наличия необходимых столбцов
                required_columns = ['batch_number', 'operation_name', 'quantity', 'operator_id', 'part_id',
                                    'machine_id']
                missing_columns = [col for col in required_columns if col not in df.columns]

                if missing_columns:
                    return JsonResponse({'status': 'error',
                                         'message': f'Отсутствуют обязательные столбцы: {", ".join(missing_columns)}'})

                # Получаем модель пользователя
                User = get_user_model()

                # Логика для сохранения данных из DataFrame в базу данных
                for index, row in df.iterrows():
                    operator_id = row['operator_id']
                    try:
                        operator = User.objects.get(id=operator_id)  # Получите объект пользователя по ID
                    except User.DoesNotExist:
                        return JsonResponse(
                            {'status': 'error', 'message': f'Пользователь с ID {operator_id} не найден.'})

                    ShiftAssignment.objects.create(
                        batch_number=row['batch_number'],
                        operation_name=row['operation_name'],
                        quantity=row['quantity'],
                        operator=operator,
                        part_id=row['part_id'],
                        machine_id=row['machine_id'],
                        date=row['date']  # Убедитесь, что у вас есть значение для даты
                    )

                # Перенаправление на страницу профиля пользователя после успешной загрузки
                return redirect('users:user_profile', pk=request.user.pk)  # Передаем ID текущего пользователя

            except Exception as e:
                return JsonResponse({'status': 'error', 'message': str(e)})

        return JsonResponse({'status': 'error', 'message': 'Ошибка при загрузке файла.'})


class CompletedShiftAssignmentView(View):
    """
    Представление для создания завершенного сменного задания.

    Это представление отображает форму для завершения задания и обрабатывает его сохранение.
    """

    model = ShiftAssignment  # Указываем модель, если это необходимо
    template_name = 'shift_assignment/completed_shift_assignment.html'

    def get(self, request, *args, **kwargs):
        """Обрабатывает GET запрос для отображения формы завершенного задания."""
        assignment_id = kwargs.get('pk')  # Получаем ID сменного задания из URL
        shift_assignment = get_object_or_404(ShiftAssignment, id=assignment_id)

        # Передаем объект сменного задания в контекст
        initial_data = {
            'operator': shift_assignment.operator,
            'operation_name': shift_assignment.operation_name,
            'machine_id': shift_assignment.machine_id,
            'part_id': shift_assignment.part_id,
            'batch_number': shift_assignment.batch_number,
            'quantity': shift_assignment.quantity,
        }

        context = {
            'form': CompletedShiftAssignmentForm(initial=initial_data),  # Заполняем форму начальными данными
            'shift_assignment': shift_assignment,
        }

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        """Обрабатывает POST запрос для сохранения завершенного задания."""
        form = CompletedShiftAssignmentForm(request.POST)

        if form.is_valid():
            # Создаем новый объект CompletedShiftAssignment
            completed_shift_assignment = form.save(commit=False)
            completed_shift_assignment.operator = request.user

            # Получаем ID сменного задания и связываем его с завершенным заданием
            assignment_id = kwargs.get('pk')
            shift_assignment = get_object_or_404(ShiftAssignment, id=assignment_id)
            completed_shift_assignment.shift_assignment = shift_assignment

            # Заполняем остальные поля из сменного задания
            completed_shift_assignment.operator = shift_assignment.operator  # Пример поля
            completed_shift_assignment.operation_name = shift_assignment.operation_name
            completed_shift_assignment.machine_id = shift_assignment.machine_id
            completed_shift_assignment.part_id = shift_assignment.part_id
            completed_shift_assignment.batch_number = shift_assignment.batch_number

            # Сохраняем объект выполненного задания в базе данных
            completed_shift_assignment.save()

            # Удаляем исходное сменное задание из базы данных
            shift_assignment.delete()  # Удаляем только ShiftAssignment

            # Перенаправляем на профиль пользователя с его ID
            return redirect('users:user_profile', pk=request.user.pk)  # Используем правильное имя маршрута

        # Если форма не валидна, повторно получаем объект сменного задания для передачи в контекст
        assignment_id = kwargs.get('pk')
        shift_assignment = get_object_or_404(ShiftAssignment, id=assignment_id)

        return render(request, self.template_name, {
            'form': form,
            'shift_assignment': shift_assignment,
        })


class CompletedShiftAssignmentUpdateView(UpdateView):
    """
    Представление для обновления завершенного сменного задания.

    Это представление обрабатывает обновление существующего завершенного задания.
    """

    model = CompletedShiftAssignment
    form_class = CompletedShiftAssignmentForm
    template_name = 'shift_assignment/completed_shift_assignment_update.html'

    def get_success_url(self):
        """Возвращает URL для перенаправления после успешного обновления."""
        return reverse_lazy('users:user_profile', kwargs={'pk': self.request.user.pk})


class DeleteCompletedShiftView(View):
    """
    Представление для удаления завершенного сменного задания.

    Это представление обрабатывает удаление существующего завершенного задания.
    """

    def post(self, request, id):
        """Обрабатывает POST запрос для удаления завершенного задания."""
        completed_shift = get_object_or_404(CompletedShiftAssignment, id=id)
        completed_shift.delete()

        return redirect('users:user_profile', pk=request.user.id)


class ShiftAssignmentDetailView(DetailView):
    """
    Представление для отображения деталей сменного задания.

    Это представление показывает информацию о конкретном задании.
    """

    model = ShiftAssignment
    template_name = 'shift_assignment/shift_assignment_detail.html'
    context_object_name = 'assignment'


class ShiftAssignmentUpdateView(UpdateView):
    """
    Представление для обновления сменного задания.

    Это представление обрабатывает обновление существующего задания.
    """

    model = ShiftAssignment
    form_class = ShiftAssignmentForm
    template_name = 'shift_assignment/shift_assignments_update.html'

    def get_success_url(self):
        """Возвращает URL для перенаправления после успешного обновления."""
        return reverse_lazy('users:user_profile', kwargs={'pk': self.request.user.pk})


class ShiftAssignmentDeleteView(LoginRequiredMixin, DeleteView):
    """
    Представление для удаления сменного задания.

    Это представление обрабатывает удаление существующего задания.
    """

    model = ShiftAssignment
    template_name = 'shift_assignment/shift_assignment_delete.html'

    def get_success_url(self):
        """Возвращает URL для перенаправления после успешного удаления."""
        return reverse_lazy('users:user_profile', kwargs={'pk': self.request.user.pk})

    def get_object(self, queryset=None):
        """Получает объект по первичному ключу (pk)."""
        return get_object_or_404(ShiftAssignment, pk=self.kwargs['pk'])

shift_assignment/templates/shift_assignment/completed_shift_assignment.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Выполненное сменное задание:{% endblock %}

{% block content %}
<div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}  <!-- Отображение формы -->
        <button type="submit" class="btn btn-success">Сохранить</button>
    </form>
</div>
{% endblock %}

<!-- Подключаем CSS файл -->
<link rel='stylesheet' href='{% static 'process_history/css/styles.css' %}' type='text/css'>

<!-- Подключаем JS файл -->
<script src='{% static 'process_history/js/scripts.js' %}'></script>

shift_assignment/templates/shift_assignment/completed_shift_assignment_update.html
{% extends "base.html" %}

{% block content %}
    <h2>Редактировать выполненное задание</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}  <!-- Отображение формы -->
        <button type="submit" class="btn btn-success">Сохранить</button>
        <a href="{% url 'users:user_profile' object.operator.pk %}" class="btn btn-secondary">Отмена</a>
    </form>
{% endblock %}

shift_assignment/templates/shift_assignment/delete_completed_shift.html
{% extends 'base.html' %}  <!-- Замените на ваш базовый шаблон -->

{% block content %}
<div class="container">
    <h2>Подтверждение удаления</h2>
    <p>Вы уверены, что хотите удалить завершенное задание с ID {{ completed_shift.id }}?</p>

    <form action="{% url 'shift_assignment:delete_completed_shift' completed_shift.id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'shift_assignment:user_profile' pk=request.user.pk %}" class="btn btn-secondary">Отменить</a>
    </form>
</div>
{% endblock %}

shift_assignment/templates/shift_assignment/shift_assignment_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Удаление сменного задания{% endblock %}

{% block content %}
<h2>Вы действительно хотите удалить это сменное задание?</h2>
<p><strong>Операция:</strong> {{ object.operation_name }}</p>
<p><strong>Дата:</strong> {{ object.date }}</p>

<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Да, удалить</button>
    <a href="{% url 'users:user_profile' request.user.pk %}" class="btn btn-secondary">Нет, отменить</a>
</form>
{% endblock %}
<!-- Подключаем CSS файл -->
<link rel='stylesheet' href='{% static ' process_history/css/styles.css' %}' type='text/css'>

<!-- Подключаем JS файл -->
<script src='{% static ' process_history/js/scripts.js' %}'></script>

shift_assignment/templates/shift_assignment/shift_assignment_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Детали сменного задания{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1>{{ assignment.title }}</h1>
    <p><strong>Дата:</strong> {{ assignment.date }}</p>
    <h3>Описание:</h3>
    <p><strong>Имя оператора:</strong> {{ assignment.operator.username }}</p>
    <p><strong>Название операции:</strong> {{ assignment.operation_name }}</p>
    <p><strong>Номер станка:</strong> {{ assignment.machine_id}}</p>
    <p><strong>Наименование детали:</strong> {{ assignment.part_id }}</p>
    <p><strong>Номер партии:</strong> {{ assignment.batch_number }}</p>
    <p><strong>Количество:</strong> {{ assignment.quantity }}</p>

    <a href="{% url 'process_history:history_process_create' assignment.id %}" class="btn btn-success">Выполнить
        задание</a>

</div>
{% endblock %}
<!-- Подключаем CSS файл -->
<link rel='stylesheet' href='{% static ' process_history/css/styles.css' %}' type='text/css'>

<!-- Подключаем JS файл -->
<script src='{% static ' process_history/js/scripts.js' %}'></script>

shift_assignment/templates/shift_assignment/shift_assignment_list.html
{% extends 'base.html' %}

{% block title %}Список сменных заданий{% endblock %}

{% block content %}  <!-- Добавлен блок для основного контента -->
<table>
    <thead>
        <tr>
            <th>Название задания</th>
            <th>Дата создания</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        {% for assignment in assignments %}
        <tr>
            <td>{{ assignment.title }}</td>
            <td>{{ assignment.created_at }}</td>
            <td><a href="{% url 'create_process_history' assignment.id %}">Просмотреть</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

shift_assignment/templates/shift_assignment/shift_assignments_detail.html
{% extends "base.html" %}

{% block title %}
Детали задания - {{ assignment.title }}
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center">Детали задания</h1>

    <main id="content" class="mt-4">
        <h2>{{ assignment.title }}</h2>
        <p><strong>Сотрудник:</strong> {{ assignment.employee }}</p>
        <p><strong>Время смены:</strong> {{ assignment.shift_time }}</p>
        <p><strong>Мастер:</strong> {{ assignment.master }}</p>
        <p><strong>Описание:</strong> {{ assignment.description }}</p>

        <div class="mt-4">
            <a href="{% url 'shift_assignment:shift_assignment_list' %}" class="btn btn-primary">Назад к списку заданий</a>
            <a href="{% url 'shift_assignment:shift_assignment_edit' pk=assignment.pk %}" class="btn btn-warning">Редактировать задание</a>
        </div>
    </main>
</div>
{% endblock %}

shift_assignment/templates/shift_assignment/shift_assignments_update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">
    <h2>Редактирование сменного задания</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Сохранить</button>
        <a href="{% url 'users:user_profile' object.operator.pk %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}
<!-- Подключаем CSS файл -->
<link rel='stylesheet' href='{% static ' process_history/css/styles.css' %}' type='text/css'>

<!-- Подключаем JS файл -->
<script src='{% static ' process_history/js/scripts.js' %}'></script>

shift_assignment/templates/shift_assignment/upload_shift_assignment.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Загрузка сменного задания{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>Загрузите сменное задание</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="file" class="form-label">Выберите файл .xls или .xlsx:</label>
            <input type="file" class="form-control" id="file" name="file" accept=".xls,.xlsx" required>
        </div>
        <button type="submit" class="btn btn-primary">Загрузить</button>
    </form>
</div>
{% endblock %}
<!-- Подключаем CSS файл -->
<link rel='stylesheet' href='{% static ' process_history/css/styles.css' %}' type='text/css'>

<!-- Подключаем JS файл -->
<script src='{% static ' process_history/js/scripts.js' %}'></script>