config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from process_history.views import HomePageView

# Определение маршрутов (URL) для проекта
urlpatterns = [
    # URL для административной панели
    path('admin/', admin.site.urls),

    # Главная страница, обрабатываемая представлением HomePageView
    path('', HomePageView.as_view(), name='home'),

    # Подключение маршрутов приложения пользователей
    path('users/', include('users.urls', namespace='users')),

    # Подключение маршрутов приложения истории процессов
    path('process_history/', include('process_history.urls', namespace='process_history')),

    # Подключение маршрутов приложения назначения смен
    path('shift_assignment/', include('shift_assignment.urls', namespace='shift_assignment')),
]

# Если проект находится в режиме отладки (DEBUG), добавляем обработку статических файлов
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shift_assignment/urls.py
from django.urls import path
from .views import (
    ShiftAssignmentUpdateView,
    ShiftAssignmentDeleteView,
    ShiftAssignmentDetailView,
    UploadShiftAssignmentView,
    CompletedShiftAssignmentView,
    CompletedShiftAssignmentUpdateView,
    DeleteCompletedShiftView
)

# Указываем пространство имен для приложения shift_assignment
app_name = 'shift_assignment'  # Убедитесь, что это указано

urlpatterns = [
    # URL для загрузки нового задания
    path('upload/', UploadShiftAssignmentView.as_view(), name='upload_shift_assignment'),

    # URL для удаления задания по его первичному ключу (pk)
    path('shift_assignment/<int:pk>/delete/', ShiftAssignmentDeleteView.as_view(), name='delete_shift'),

    # URL для просмотра завершенного задания по его первичному ключу (pk)
    path('completed/<int:pk>/', CompletedShiftAssignmentView.as_view(), name='completed_shift_assignment'),

    # URL для просмотра деталей задания по его первичному ключу (pk)
    path('detail/<int:pk>/', ShiftAssignmentDetailView.as_view(), name='shift_assignment_detail'),

    # URL для обновления задания по его первичному ключу (pk)
    path('shift_assignment/<int:pk>/update/', ShiftAssignmentUpdateView.as_view(), name='update_shift'),

    # URL для обновления завершенного задания по его первичному ключу (pk)
    path('completed_shift_assignment/<int:pk>/update/', CompletedShiftAssignmentUpdateView.as_view(),
         name='completed_shift_assignment_update'),  # Новый маршрут

    # URL для удаления завершенного задания по его идентификатору (id)
    path('delete_completed_shift/<int:id>/', DeleteCompletedShiftView.as_view(), name='delete_completed_shift'),
]

users/urls.py
from django.urls import path
from .views import UserRegisterView, UserLoginView, UserLogoutView, UserProfileView, UserListView, UserUpdateView

app_name = 'users'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='user_register'),  # Регистрация
    path('login/', UserLoginView.as_view(), name='login_user'),  # Вход
    path('logout/', UserLogoutView.as_view(), name='logout'),  # Выход
    path('update/<int:pk>/', UserUpdateView.as_view(), name='update_user'),  # Обновление пользователя
    path('profile/<int:pk>/', UserProfileView.as_view(), name='user_profile'),  # Профиль пользователя
    path('users/', UserListView.as_view(), name='user_list'),  # Список пользователей
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _

# Определение параметров для полей, которые могут быть пустыми
NULLABLE = {'blank': True, 'null': True}


class UserRoles(models.TextChoices):
    """
    Определение ролей пользователей с использованием TextChoices.

    Это перечисление содержит доступные роли пользователей в системе:
    - Оператор
    - Мастер
    - Администратор
    """
    OPERATOR = 'operator', _('Operator')
    MASTER = 'master', _('Master')
    ADMIN = 'admin', _('Administrator')


class User(AbstractUser):
    """
    Модель пользователя, расширяющая стандартную модель AbstractUser.

    Эта модель добавляет дополнительные поля и функциональность для пользователей системы.
    """

    is_staff = models.BooleanField(default=False)  # Указывает, является ли пользователь сотрудником
    first_name = models.CharField(max_length=30, blank=False, null=False, default='имя оператора',
                                  verbose_name="имя сотрудника")
    last_name = models.CharField(max_length=30, blank=False, null=False, default='фамилия оператора',
                                 verbose_name="фамилия сотрудника")

    username = models.CharField(max_length=150, unique=True, blank=False, null=False)  # Уникальное имя пользователя
    password = models.CharField(max_length=255, verbose_name="пароль")  # Пароль пользователя

    role = models.CharField(max_length=9, choices=UserRoles.choices, default=UserRoles.OPERATOR,
                            verbose_name="должность")  # Роль пользователя
    is_active = models.BooleanField(default=True, verbose_name='active',
                                    **NULLABLE)  # Указывает, активен ли пользователь

    USERNAME_FIELD = "username"  # Поле для аутентификации
    REQUIRED_FIELDS = ['first_name', 'last_name']  # Обязательные поля при создании пользователя

    def __str__(self):
        """Возвращает строковое представление объекта пользователя."""
        return f'{self.first_name} {self.last_name}'

    class Meta:
        """Метаданные модели."""
        verbose_name = 'User'  # Человекочитаемое имя в единственном числе
        verbose_name_plural = 'Users'  # Человекочитаемое имя во множественном числе
        ordering = ['id']  # Сортировка по ID по умолчанию

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from users.models import User
from django.utils.translation import gettext_lazy as _


class StyleFormMixin:
    """
    Миксин для стилизации форм.

    Этот миксин добавляет класс 'form-control' ко всем полям формы,
    чтобы применить стили Bootstrap.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserForm(StyleFormMixin, forms.ModelForm):
    """
    Форма для создания или редактирования пользователя.

    Эта форма используется для ввода данных о пользователе,
    включая имя пользователя, имя и фамилию.
    """

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'role',)


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    """
    Форма для регистрации нового пользователя.

    Эта форма используется для создания нового пользователя с проверкой пароля.
    """

    class Meta:
        model = User
        fields = ('username',)

    def clean_password2(self):
        """
        Проверка соответствия паролей.

        Если введенные пароли не совпадают, выбрасывает ValidationError.
        """
        temp_data = self.cleaned_data
        if temp_data['password1'] != temp_data['password2']:
            raise forms.ValidationError('password_mismatch')
        return temp_data['password2']


class UserLoginForm(AuthenticationForm):
    """
    Форма для аутентификации пользователя.

    Эта форма проверяет правильность введенных имени пользователя и пароля.
    """

    def clean(self):
        """Проверяет наличие ошибок в форме и генерирует сообщение об ошибке."""
        super().clean()
        if self.errors:
            error_messages = []
            for field in self.errors:
                error_messages.extend(self.errors[field])
            if error_messages:
                raise forms.ValidationError(_('Пожалуйста, введите правильные имя пользователя и пароль. '
                                              'Оба поля могут быть чувствительны к регистру.'))

        return self.cleaned_data


class UserUpdateForm(StyleFormMixin, forms.ModelForm):
    """
    Форма для обновления данных пользователя.

    Эта форма используется для редактирования информации о пользователе.
    """

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name',)

users/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import redirect, get_object_or_404, render
from django.views.generic import CreateView, UpdateView, ListView, DetailView

from django.urls import reverse_lazy
from users.models import User, UserRoles
from users.forms import UserRegisterForm, UserLoginForm, UserUpdateForm, UserForm

from shift_assignment.models import ShiftAssignment, CompletedShiftAssignment


class UserRegisterView(CreateView):
    """
    Представление для регистрации нового пользователя.

    Это представление использует форму регистрации и перенаправляет на страницу входа после успешной регистрации.
    """
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login_user')  # Убедитесь, что это имя маршрута соответствует вашему urls.py
    template_name = 'users/register_user.html'


class UserLoginView(LoginView):
    """
    Представление для входа пользователя.

    Это представление проверяет учетные данные пользователя и перенаправляет на профиль после успешного входа.
    """
    form_class = UserLoginForm
    template_name = 'users/login_user.html'

    def form_valid(self, form):
        """Обрабатывает успешное заполнение формы входа."""
        user = form.get_user()
        login(self.request, user)
        return redirect('users:user_profile', pk=user.pk)


class UserProfileView(LoginRequiredMixin, DetailView):
    """
    Представление для отображения профиля пользователя.

    Это представление показывает информацию о пользователе и связанные с ним задания.
    """
    model = User
    template_name = 'users/user_profile.html'
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        """Добавляет дополнительные данные в контекст профиля пользователя."""
        context = super().get_context_data(**kwargs)
        user_role = self.request.user.role  # Получаем роль пользователя

        # Устанавливаем can_create_shift для администраторов и мастеров
        context['can_create_shift'] = user_role in [UserRoles.ADMIN, UserRoles.MASTER]

        # Получаем текущие сменные задания в зависимости от роли пользователя
        if user_role in [UserRoles.ADMIN, UserRoles.MASTER]:
            context['shift_assignments'] = ShiftAssignment.objects.all()  # Все задания для админа и мастера
        elif user_role == UserRoles.OPERATOR:
            context['shift_assignments'] = ShiftAssignment.objects.filter(operator=self.request.user)

        # Получаем выполненные сменные задания для текущего пользователя и всех мастеров и администраторов
        if user_role in [UserRoles.ADMIN, UserRoles.MASTER]:
            context[
                'completed_assignments'] = CompletedShiftAssignment.objects.all()  # Все выполненные задания для админа и мастера
        else:
            context['completed_assignments'] = CompletedShiftAssignment.objects.filter(
                operator=self.request.user)  # Только для оператора

        # Передаем строковые значения ролей в контекст
        context['is_admin'] = user_role == UserRoles.ADMIN
        context['is_master'] = user_role == UserRoles.MASTER
        context['is_operator'] = user_role == UserRoles.OPERATOR

        return context


class UserUpdateView(UpdateView):
    """
    Представление для обновления данных пользователя.

    Это представление позволяет пользователю обновить свои данные.
    """
    model = User
    form_class = UserUpdateForm
    template_name = 'users/update_user.html'

    def get_success_url(self):
        """Возвращает URL для перенаправления после успешного обновления."""
        return reverse_lazy('users:user_profile', kwargs={'pk': self.object.pk})


class UserLogoutView(LogoutView):
    """
    Представление для выхода пользователя из системы.

    Это представление обрабатывает выход и перенаправляет на страницу входа.
    """

    template_name = 'users/logout_user.html'
    next_page = reverse_lazy('users:login_user')


class UserListView(LoginRequiredMixin, ListView):
    """
    Представление для отображения списка пользователей.

    Это представление показывает всех активных пользователей системы.
    """

    model = User
    extra_context = {
        'title': 'Сотрудники УМКИ:'
    }

    template_name = 'users/users.html'

    def get_queryset(self):
        """Фильтрует список пользователей по активности."""
        queryset = super().get_queryset()
        queryset = queryset.filter(is_active=True)  # Показывает только активных пользователей
        return queryset


class UserViewProfileView(DetailView):
    """
    Представление для просмотра профиля другого пользователя.

    Это представление отображает информацию о выбранном пользователе.
    """

    model = User
    template_name = 'users/user_view_profile.html'

users/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

users/templates/users/login.html
{% extends "base.html" %}  <!-- Наследование от базового шаблона -->

{% block title %}Вход в систему{% endblock %}  <!-- Переопределение заголовка страницы -->

{% block content %}
<div class="container mt-5">
    <h2>Вход в систему</h2>

    {% if error_message %}
        <div class="alert alert-danger">{{ error_message }}</div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Имя пользователя:</label>
            <input type="text" name="username" id="username" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="password">Пароль:</label>
            <input type="password" name="password" id="password" class="form-control" required>
        </div>

        <button type="submit" class="btn btn-primary">Войти</button>
    </form>

    <hr>

</div>
{% endblock %}

users/templates/users/login_user.html
{% extends "base.html" %}  <!-- Наследование от базового шаблона -->
{% load static %}
{% block title %}Вход в систему{% endblock %}  <!-- Переопределение заголовка страницы -->

{% block content %}
<div class="container mt-5">
    <h2>Вход в систему</h2>

    {% if error_message %}
    <div class="alert alert-danger">{{ error_message }}</div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Имя пользователя:</label>
            <input type="text" name="username" id="username" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="password">Пароль:</label>
            <input type="password" name="password" id="password" class="form-control" required>
        </div>

        <button type="submit" class="btn btn-primary">Войти</button>
    </form>

    <hr>

    <!-- Кнопка для перехода на страницу регистрации -->
    <form action="{% url 'users:user_register' %}" method="get" class="d-inline">
        <button type="submit" class="btn btn-success">Зарегистрироваться</button>
    </form>
</div>
{% endblock %}
<!-- Подключаем CSS файл -->
<link rel='stylesheet' href='{% static ' process_history/css/styles.css' %}' type='text/css'>

<!-- Подключаем JS файл -->
<script src='{% static ' process_history/js/scripts.js' %}'></script>

users/templates/users/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>вы вышли из аккаунта</h1>
</body>
</html>

users/templates/users/logout_user.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Вы успешно вышли из Вашего аккаунта!</h1>
<p>Спасибо за использование нашего сервиса.</p>
<a href="{% url 'users:login_user' %}">Нажмите сюда, чтобы снова войти</a>
{% endblock %}

users/templates/users/register_user.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Регистрация пользователя</div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p}}
                    <button type="submit" class="btn btn-success">Регистрация</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/update_user.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Редактирование пользователя
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Профиль пользователя{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>{{ user.first_name }} {{ user.last_name }}</h2>
    <a href="{% url 'users:update_user' user.pk %}" class="btn btn-secondary mb-3">Редактировать профиль</a>

    {% if can_create_shift %}
    <br>
    <a href="{% url 'shift_assignment:upload_shift_assignment' %}" class="btn btn-primary mb-3">Создать сменное
        задание</a>
    {% endif %}

    <h3 style="color: #1184f0;">Сменные задания:</h3>
    <div class="row">
        {% for assignment in shift_assignments %}
        <div class="col-md-4 mb-4">
            <div class="card">
                <div class="card-body">

                    <p><strong>Дата:</strong> {{ assignment.date }}</p>
                    <p><strong>Оператор:</strong> {{ assignment.operator.username }}</p>
                    <p><strong>Номер станка:</strong> {{ assignment.machine_id }}</p>
                    <p><strong>Наименование детали:</strong> {{ assignment.part_id }}</p>
                    <p><strong>Номер партии:</strong> {{ assignment.batch_number }}</p>
                    <p><strong>Количество:</strong> {{ assignment.quantity }}</p>

                    {% if is_admin or is_master %}
                    <a href="{% url 'shift_assignment:update_shift' assignment.id %}" class="btn btn-warning">Редактировать</a>
                    <form action="{% url 'shift_assignment:delete_shift' assignment.id %}" method="post"
                          style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Удалить</button>
                    </form>
                    {% else %}
                    <a href="{% url 'shift_assignment:shift_assignment_detail' assignment.id %}" class="btn btn-info">Подробнее</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% empty %}
        <p>Нет активных сменных заданий.</p>
        {% endfor %}
    </div>
    <h3 style="color: #2e9409;">Выполненные сменные задания:</h3>
    <div class="row">
        {% for completed in completed_assignments %}
        <div class="col-md-4">
            <div class="card mb-4">
                <div class="card-body">
                    <h5 class="card-title">{{ completed.operation_name }}</h5>
                    <p class="card-text"><strong>Оператор:</strong> {{ completed.operator.username }}</p>
                    <p class="card-text"><strong>Номер станка:</strong> {{ completed.machine_id }}</p>
                    <p class="card-text"><strong>Наименование детали:</strong> {{ completed.part_id }}</p>
                    <p class="card-text"><strong>Номер партии:</strong> {{ completed.batch_number }}</p>
                    <p class="card-text"><strong>Количество:</strong> {{ completed.quantity }}</p>
                    <p class="card-text"><strong>Количество брака:</strong> {{ completed.defect_quantity }}</p>
                    <p class="card-text"><strong>Причина остановки:</strong> {{ completed.stop_reason }}</p>

                    <!-- Кнопка редактирования для завершенных заданий -->
                    <a href="{% url 'shift_assignment:completed_shift_assignment_update' completed.id %}"
                       class="btn btn-warning">Редактировать</a>

                    <!-- Условие для отображения кнопки удаления -->
                    {% if is_admin or is_master %}
                    <form action="{% url 'shift_assignment:delete_completed_shift' completed.id %}" method="post"
                          style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Удалить</button>
                    </form>

                    {% endif %}
                </div>
            </div>
        </div>
        {% empty %}
        <p>Нет выполненных заданий.</p>
        {% endfor %}
    </div>
</div>

{% endblock %}
<!-- Подключаем CSS файл -->
<link rel='stylesheet' href='{% static ' process_history
/css/styles.css' %}' type='text/css'>

<!-- Подключаем JS файл -->
<script src='{% static ' process_history
/js/scripts.js' %}'></script>

users/templates/users/users.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}

<div class="container">
    <div class="row">
        {% for objects in objects_list %}
        {% include 'user/includes/inc_user_card.html' with object=object %}
        {% endfor %}
    </div>
</div>

{% endblock %}