config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from process_history.views import HomePageView

# Определение маршрутов (URL) для проекта
urlpatterns = [
    # URL для административной панели
    path('admin/', admin.site.urls),

    # Главная страница, обрабатываемая представлением HomePageView
    path('', HomePageView.as_view(), name='home'),

    # Подключение маршрутов приложения пользователей
    path('users/', include('users.urls', namespace='users')),

    # Подключение маршрутов приложения истории процессов
    path('process_history/', include('process_history.urls', namespace='process_history')),

    # Подключение маршрутов приложения назначения смен
    path('shift_assignment/', include('shift_assignment.urls', namespace='shift_assignment')),
]

# Если проект находится в режиме отладки (DEBUG), добавляем обработку статических файлов
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

process_history/urls.py
from django.urls import path
from .views import HomePageView, SaveProcessHistoryView, HistoryProcessCreateView

# Указываем пространство имен для приложения process_history
app_name = 'process_history'

urlpatterns = [
    # URL для создания новой записи истории процесса по первичному ключу (pk)
    path('create/<int:pk>/', HistoryProcessCreateView.as_view(), name='history_process_create'),

    # URL для главной страницы приложения
    path('', HomePageView.as_view(), name='home'),

    # URL для сохранения истории процесса, связанного с заданием (assignment_id)
    path('save_process_history/<int:assignment_id>/', SaveProcessHistoryView.as_view(), name='save_process_history'),
]

shift_assignment/urls.py
from django.urls import path
from .views import (
    ShiftAssignmentUpdateView,
    ShiftAssignmentDeleteView,
    ShiftAssignmentDetailView,
    UploadShiftAssignmentView,
    CompletedShiftAssignmentView,
    CompletedShiftAssignmentUpdateView,
    DeleteCompletedShiftView
)

# Указываем пространство имен для приложения shift_assignment
app_name = 'shift_assignment'  # Убедитесь, что это указано

urlpatterns = [
    # URL для загрузки нового задания
    path('upload/', UploadShiftAssignmentView.as_view(), name='upload_shift_assignment'),

    # URL для удаления задания по его первичному ключу (pk)
    path('shift_assignment/<int:pk>/delete/', ShiftAssignmentDeleteView.as_view(), name='delete_shift'),

    # URL для просмотра завершенного задания по его первичному ключу (pk)
    path('completed/<int:pk>/', CompletedShiftAssignmentView.as_view(), name='completed_shift_assignment'),

    # URL для просмотра деталей задания по его первичному ключу (pk)
    path('detail/<int:pk>/', ShiftAssignmentDetailView.as_view(), name='shift_assignment_detail'),

    # URL для обновления задания по его первичному ключу (pk)
    path('shift_assignment/<int:pk>/update/', ShiftAssignmentUpdateView.as_view(), name='update_shift'),

    # URL для обновления завершенного задания по его первичному ключу (pk)
    path('completed_shift_assignment/<int:pk>/update/', CompletedShiftAssignmentUpdateView.as_view(),
         name='completed_shift_assignment_update'),  # Новый маршрут

    # URL для удаления завершенного задания по его идентификатору (id)
    path('delete_completed_shift/<int:id>/', DeleteCompletedShiftView.as_view(), name='delete_completed_shift'),
]

users/urls.py
from django.urls import path
from .views import UserRegisterView, UserLoginView, UserLogoutView, UserProfileView, UserListView, UserUpdateView

app_name = 'users'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='user_register'),  # Регистрация
    path('login/', UserLoginView.as_view(), name='login_user'),  # Вход
    path('logout/', UserLogoutView.as_view(), name='logout'),  # Выход
    path('update/<int:pk>/', UserUpdateView.as_view(), name='update_user'),  # Обновление пользователя
    path('profile/<int:pk>/', UserProfileView.as_view(), name='user_profile'),  # Профиль пользователя
    path('users/', UserListView.as_view(), name='user_list'),  # Список пользователей
]

process_history/forms.py
from django import forms
from django.core.exceptions import ValidationError
from process_history.models import ProcessHistory
from shift_assignment.models import ShiftAssignment
from users.forms import StyleFormMixin


class ProcessHistoryForm(StyleFormMixin, forms.ModelForm):
    """
    Форма для ввода данных о процессе.

    Эта форма используется для создания или редактирования записей
    в модели ProcessHistory. Она включает поля для проверки
    различных характеристик процесса.
    """

    # Поле для ввода количества брака (необязательное)
    defect_quantity = forms.IntegerField(required=False, label='Количество брака')

    # Поле для выбора причины остановки процесса
    stop_reason = forms.ChoiceField(
        choices=[
            ('СлНал', 'СлНал'),
            ('ТОиР', 'ТОиР'),
            ('Прочее', 'Прочее'),
        ],
        label='Причина остановки'
    )

    # Поле для ввода специальных характеристик
    special_characteristics = forms.DecimalField(
        label='Специальные характеристики',
        max_digits=5,
        decimal_places=3,
        required=False
    )

    class Meta:
        model = ProcessHistory  # Модель, с которой работает форма
        fields = [
            'roughness_check',
            'defects_check',
            'threading_check',
            'diameter_check',
            'value',
            'detail_quantity',
            'control_code',
            'mark_yes_no',
            'defect_quantity',  # Добавляем поле количества брака
            'stop_reason',  # Добавляем поле причины остановки
            'special_characteristics'  # Добавляем поле специальных характеристик
        ]

    def clean_value(self):
        """
        Валидация поля value.

        Проверяет, что значение находится в заданном диапазоне и округляет его до трех знаков после запятой.
        """
        value = self.cleaned_data.get('value')

        if value is not None:
            # Проверка диапазона
            if not (21.95 <= value <= 22):
                raise ValidationError('Значение должно быть в диапазоне от 21.95 до 22.')

            # Округление до трех знаков после запятой
            return round(value, 3)

        return value


class QualityControlForm(StyleFormMixin, forms.Form):
    """
    Форма для контроля качества.

    Эта форма используется для ввода данных о шероховатости и отсутствии дефектов.
    """

    roughness = forms.DecimalField(label='Шероховатость (мкм)', max_digits=5, decimal_places=2)

    defects_absent = forms.BooleanField(required=False, label='Отсутствие рисок, канавок и т.д.')


class SaveProcessHistoryForm(StyleFormMixin, forms.ModelForm):
    """Форма для сохранения истории процесса."""

    class Meta:
        model = ShiftAssignment  # Укажите модель, с которой работаете
        fields = [
            'operator',
            'master',
            'operation_name',
            'machine_id',
            'part_id',
            'batch_number',
            'quantity',
            'file'
        ]

        widgets = {
            # Применяем виджеты для улучшения отображения полей
            'date': forms.DateInput(attrs={'type': 'date'}),
        }

    def clean_quantity(self):
        """
        Валидация поля quantity.

        Проверяет, что количество больше нуля.
        """
        quantity = self.cleaned_data.get('quantity')

        if quantity <= 0:
            raise forms.ValidationError("Количество должно быть больше нуля.")

        return quantity

process_history/views.py
import logging
from django.urls import reverse
from django.views.generic import TemplateView
from shift_assignment.models import ShiftAssignment, CompletedShiftAssignment
from .forms import ProcessHistoryForm, SaveProcessHistoryForm
from .models import ProcessHistory
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View

# Настройка логирования
logger = logging.getLogger(__name__)


class HomePageView(TemplateView):
    """
    Представление для главной страницы приложения.

    Отображает шаблон home.html и передает в контекст URL для входа.
    """
    template_name = 'process_history/home.html'  # Убедитесь, что у вас есть этот шаблон

    def get_context_data(self, **kwargs):
        """
        Добавляет дополнительные данные в контекст для шаблона.

        Параметры:
        **kwargs: Дополнительные параметры контекста.

        Возвращает:
        dict: Обновленный контекст с URL для входа.
        """
        context = super().get_context_data(**kwargs)
        context['login_url'] = reverse('users:login_user')  # Используйте правильное имя
        return context


class HistoryProcessCreateView(View):
    """
    Представление для создания записи истории процесса.

    Обрабатывает GET и POST запросы для создания новой записи в модели ProcessHistory.
    """
    model = ProcessHistory
    form_class = ProcessHistoryForm
    template_name = 'process_history/history_process_create.html'

    def get(self, request, pk):
        """
        Обрабатывает GET запрос для отображения формы создания записи.

        Параметры:
        request: HTTP запрос.
        pk (int): Первичный ключ сменного задания.

        Возвращает:
        HttpResponse: Отрендеренный шаблон с контекстом.
        """
        shift_assignment = get_object_or_404(ShiftAssignment, pk=pk)

        context = {
            'operator': shift_assignment.operator.username if shift_assignment.operator else 'Неизвестно',
            'operation_name': shift_assignment.operation_name,
            'machine_id': shift_assignment.machine_id,
            'part_id': shift_assignment.part_id,
            'batch_number': shift_assignment.batch_number,
            'shift_assignment': shift_assignment,
            'form': ProcessHistoryForm(),
            'process_history': ProcessHistory.objects.filter(user=request.user),
            'assignment_id': pk  # Передаем assignment_id в контекст
        }

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        """
        Обрабатывает POST запрос для сохранения новой записи истории процесса.

        Параметры:
        request: HTTP запрос.

        Возвращает:
        HttpResponse: Перенаправление или отрендеренный шаблон с ошибками формы.
        """
        form = ProcessHistoryForm(request.POST)

        if form.is_valid():
            process_history = form.save(commit=False)
            process_history.user = request.user

            pk = self.kwargs.get('pk')  # Получаем ID сменного задания из URL
            shift_assignment = get_object_or_404(ShiftAssignment, pk=pk)

            # Заполнение полей на основе сменного задания
            process_history.machine_id = shift_assignment.machine_id
            process_history.part_id = shift_assignment.part_id
            process_history.batch_number = shift_assignment.batch_number

            process_history.save()

            return redirect('/process_history/')

        return render(request, self.template_name, {'form': form})


class SaveProcessHistoryView(View):
    """
    Представление для сохранения истории процесса.

    Обрабатывает GET и POST запросы для сохранения данных о процессе.
    """
    model = ProcessHistory
    form_class = SaveProcessHistoryForm
    template_name = 'process_history/save_process_history.html'

    def get(self, request, assignment_id):
        """
        Обрабатывает GET запрос для отображения формы сохранения истории процесса.

        Параметры:
        request: HTTP запрос.
        assignment_id (int): ID сменного задания.

        Возвращает:
        HttpResponse: Отрендеренный шаблон с контекстом.
        """
        shift_assignment = get_object_or_404(ShiftAssignment, id=assignment_id)

        context = {
            'shift_assignment': shift_assignment,
            'form': ProcessHistoryForm(),
        }

        return render(request, self.template_name, context)

    def post(self, request, assignment_id):
        """
        Обрабатывает POST запрос для сохранения данных о процессе.

        Параметры:
        request: HTTP запрос.
        assignment_id (int): ID сменного задания.

        Возвращает:
        HttpResponse: Перенаправление на профиль пользователя или отрендеренный шаблон с ошибками формы.
        """

        form = ProcessHistoryForm(request.POST)

        if form.is_valid():
            # Создаем новый объект CompletedShiftAssignment на основе данных формы
            completed_shift_assignment = CompletedShiftAssignment(
                operator=request.POST.get('operator'),
                operation_name=request.POST.get('operation_name'),
                machine_id=request.POST.get('machine_id'),
                part_id=request.POST.get('part_id'),
                batch_number=request.POST.get('batch_number'),
                quantity=request.POST.get('quantity'),
                defect_quantity=request.POST.get('defect_quantity', 0),  # Дефолтное значение 0
                stop_reason=request.POST.get('stop_reason', 'Работа в нормальном режиме')  # Дефолтное значение
            )

            # Сохраняем запись в базе данных
            completed_shift_assignment.save()

            # Перенаправление на профиль пользователя после сохранения
            return redirect(f'/users/profile/{request.user.id}/')  # Замените на правильный URL для профиля

        return render(request, self.template_name, {'form': form})

process_history/templates/process_history/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

process_history/templates/process_history/history_process_create.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="d-flex justify-content-between align-items-center">
    <h1 style="margin-top: 40px; margin-bottom: 20px;">История процесса</h1>
    <a href="{% url 'shift_assignment:completed_shift_assignment' shift_assignment.id %}" class="btn btn-primary"
       style="margin-top: 40px;">Закончить сменное задание</a>
</div>


<form id="parameterForm">
    {% csrf_token %}
    <table class="table">
        <thead>
        <tr>
            <th><strong>username:</strong></th>
            <th><strong>Название операции:</strong></th>
            <th><strong>Номер станка:</strong></th>
            <th><strong>Наименование детали:</strong></th>
            <th><strong>Номер партии:</strong></th>
        </tr>
        <tr>
            <td>{{ operator }}</td>
            <td>{{ operation_name }}</td>
            <td>{{ machine_id }}</td>
            <td>{{ part_id }}</td>
            <td>{{ batch_number }}</td>
        </tr>
        </thead>
    </table>
    <br>

    <!-- Карточка для параметров детали -->
    <div class="card" style="margin: 20px 0; width: 100%; border-width: 2px; border-color: #808080; border-style: solid;
     overflow: hidden;">
        <div class="card-header">
            <h2>Параметры детали:</h2>
        </div>
        <div class="card-body" style="display: flex; flex-wrap: wrap; justify-content: space-between;">
            <!-- Первый столбик -->
            <div style="flex: 1; margin-right: 10px; max-width: 48%;">
                <table class="table">
                    <tbody>
                    <tr>
                        <td>Шероховатость:</td>
                        <td class="form_toggle">
                            <div class="form_toggle-item item-1">
                                <input type="radio" name="roughness" value="+" id="roughness_yes" checked/>
                                <label for="roughness_yes">+</label>
                            </div>
                            <div class="form_toggle-item item-2">
                                <input type="radio" name="roughness" value="-" id="roughness_no"/>
                                <label for="roughness_no">-</label>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>Специальная характеристика:</td>
                        <td style="padding: 5px;">
                            <input type="number" id="specialCharacteristic" name="value"
                                   min="21.95" max="22" step="0.001" placeholder="от 21.95 до 22"
                                   required style="width: 150px; -moz-appearance: textfield; /* Для Firefox */
               -webkit-appearance: none; /* Для Chrome, Safari и Opera */
               appearance: none; /* Для других браузеров */
               "/>
                        </td>
                    </tr>

                    <script>
                        document.getElementById('specialCharacteristic').addEventListener('blur', function() {
                            const value = parseFloat(this.value);
                            const min = 21.95;
                            const max = 22;

                            // Проверяем только если значение не пустое
                            if (!isNaN(value)) {
                                if (value < min || value > max) {
                                    // Если значение вне диапазона, показываем предупреждение
                                    alert(`Пожалуйста, введите значение в диапазоне от ${min} до ${max}.`);
                                    this.value = ''; // Очищаем поле
                                }
                            }
                        });
                    </script>
                    <tr>
                        <td>Внешний вид:</td>
                        <td class="form_toggle">
                            <div class="form_toggle-item item-1">
                                <input type="radio" name="appearance" value="+" id="appearance_yes" checked/>
                                <label for="appearance_yes">+</label>
                            </div>
                            <div class="form_toggle-item item-2">
                                <input type="radio" name="appearance" value="-" id="appearance_no"/>
                                <label for="appearance_no">-</label>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>Наличие резьбы и отверстия под шплинт:</td>
                        <td class="form_toggle">
                            <div class="form_toggle-item item-1">
                                <input type="radio" name="thread_hole" value="+" id="thread_hole_yes" checked/>
                                <label for="thread_hole_yes">+</label>
                            </div>
                            <div class="form_toggle-item item-2">
                                <input type="radio" name="thread_hole" value="-" id="thread_hole_no"/>
                                <label for="thread_hole_no">-</label>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>Размер галтели:</td>
                        <td class="form_toggle">
                            <div class="form_toggle-item item-1">
                                <input type="radio" name="galtel_size" value="+" id="galtel_size_yes" checked/>
                                <label for="galtel_size_yes">+</label>
                            </div>
                            <div class="form_toggle-item item-2">
                                <input type="radio" name="galtel_size" value="-" id="galtel_size_no"/>
                                <label for="galtel_size_no">-</label>
                            </div>
                        </td>
                    </tr>

                    </tbody>
                </table>

            </div>

            <!-- Второй столбик -->
            <div style="flex: 1; margin-left: 10px; max-width: 48%;">
                <table class="table">
                    <tbody>

                    <!-- Поле для количества деталей -->
                    <tr>
                        <td>Количество деталей:</td>
                        <td><input type="number" id="quantity" name="detail_quantity"
                                   placeholder="Введите количество" value="1"
                                   style="width: 80px;"/></td>
                    </tr>

                    <!-- Поле для кода контроля -->
                    <tr>
                        <td>Код контроля:</td>
                        <td><select id="controlCode">
                            <option value='1'>1</option>
                            <option value='2'>2</option>
                            <option value='3'>3</option>
                            <option value='4'>4</option>
                            <option value='5'>5</option>
                            <option value='6'>6</option>
                            <option value='3;2'>3;2</option>
                        </select></td>
                    </tr>

                    <!-- Поле для маркировки да/нет -->
                    <tr>
                        <td>Маркировка да/нет:</td>
                        <td class='form_toggle'>
                            <div class='form_toggle-item item-1'>
                                <input type='radio' name='mark_yes_no' value='Да' id='mark_yes' checked/>
                                <label for='mark_no' class='label-no'>Да</label> <!-- Зеленый цвет -->
                            </div>
                            <div class='form_toggle-item item-2'>
                                <input type='radio' name='mark_yes_no' value='Нет' id='mark_no'/>
                                <label for='mark_yes' class='label-yes'>Нет</label> <!-- Красный цвет -->
                            </div>
                        </td>
                    </tr>

                    </tbody>
                </table>
                <div style="display: flex; align-items: flex-start;">
                    <button type='button' id='addMeasurementButton'
                            class='btn-new'
                            style="
                width: 160px; /* Ширина кнопки */
                height: 55px; /* Высота кнопки */
                font-size: 20px; /* Увеличенный размер шрифта */
                padding: 5px 10px; /* Уменьшенные отступы (верх/низ, лево/право) */
                cursor: pointer;
                margin-right: 25px;">
                        Новый замер
                    </button>
                    <p style="font-size: 14px; margin: 0;"> Коды контроля:<br>
                        1-периодический контроль<br>
                        2-запуск, замер первых деталей<br>
                        3-замена инструмента/оснастки<br>
                        4-корректировка параметров<br>
                        5-ремонт оборудования<br>
                        6-контроль последней детали
                    </p>
                </div>
            </div>

        </div>

    </div>


    <h2 style="margin: 40px auto 0; text-align: center;">Таблица параметров</h2>

    <table class="table" style="margin-left: 20px; margin-right: 20px;"> <!-- Добавлены отступы -->
        <thead>
        <tr>
            <th>Колич.</th>
            <th>Шерох.</th>
            <th>Спец. харак.</th>
            <th>Внеш. вид</th>
            <th>Резьб./отверст.</th>
            <th>Галтель</th>
            <th>Код</th>
            <th>Да/Нет</th>
        </tr>
        </thead>
        <tbody id="parametersTableBody">
        <!-- Записи будут добавляться сюда -->
        </tbody>
    </table>
</form>
{% endblock %}

<!-- Подключаем CSS файл -->
<link rel='stylesheet' href='{% static ' process_history/css/styles.css' %}' type='text/css'>

<!-- Подключаем JS файл -->
<script src='{% static ' process_history/js/scripts.js' %}'></script>

process_history/templates/process_history/home.html
{% extends "base.html" %}  <!-- Наследование от базового шаблона -->
{% load static %}
{% block title %}Главная страница{% endblock %}  <!-- Переопределение заголовка страницы -->

{% block content %}
<div class="text-lift" style="position: relative; height: 100vh; margin-top: 20px; display: flex; flex-direction: column; justify-content: flex-start; align-items: center; z-index: 1;">
    <div style="position: relative; z-index: 2; margin-top: 40px; padding: 15px; background-color: rgba(255, 255, 255, 0.7); border-radius: 10px;">
        <h3 style="color: black; text-align: center;">В этом приложении вы можете эффективно управлять своими сменными заданиями и отслеживать историю процессов.</h3>
        <h3 style="color: black; text-align: center;">Пожалуйста, авторизуйтесь, чтобы начать работу и получить доступ ко всем функциям приложения.</h3>
    </div>
    <div style="background-image: url('https://belmag.ru/img/cms/mekhanicheskaya_obrabotka/Machining.jpg'); background-size: cover; background-position: center; background-repeat: no-repeat; position: absolute; top: 0; left: 0; right: 0; bottom: 0;"></div>
</div>

{% endblock %}

<!-- Подключаем CSS файл -->
<link rel='stylesheet' href='{% static ' process_history/css/styles.css' %}' type='text/css'>

<!-- Подключаем JS файл -->
<script src='{% static ' process_history/js/scripts.js' %}'></script>

process_history/templates/process_history/process_history.html
{% extends "base.html" %}  <!-- Наследование от базового шаблона -->

{% block title %}Заполнение истории процесса{% endblock %}  <!-- Переопределение заголовка страницы -->

{% block content %}
<div class="container mt-5">
    <h1 class="text-center">Заполнение истории процесса</h1>

    <form method="POST" action="{% url 'process_history:save_process_history' task_id=task.id %}">
        {% csrf_token %}
        <table class="table table-bordered mt-4">
            <thead class="thead-light">
                <tr>
                    <th>Код контроля</th>
                    <th>Отметка (Да/Нет)</th>
                    <th>Количество деталей</th>
                    <th>Параметры</th>
                </tr>
            </thead>
            <tbody id="process-table-body">
                {% for parameter in parameters %}
                <tr>
                    <td><input type="text" name="control_code_{{ forloop.counter }}" class="form-control" required></td>
                    <td>
                        <select name="mark_{{ forloop.counter }}" class="form-control">
                            <option value="yes">Да</option>
                            <option value="no">Нет</option>
                        </select>
                    </td>
                    <td><input type="number" name="quantity_{{ forloop.counter }}" min="0" class="form-control" required></td>
                    <td><input type="checkbox" name="param_count_{{ forloop.counter }}" value="+"></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <!-- Кнопка "Сохранить" -->
        <button type="submit" class="btn btn-success btn-block">Сохранить</button>
    </form>

</div>
{% endblock %}

process_history/templates/process_history/save_process_history.html
{% extends 'base.html' %}

{% block title %}Выполненное сменное задание:{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1>Выполненное сменное задание</h1>
    <form method="POST">
        {% csrf_token %}

        <div class="mb-3">
            <label for="operator_name" class="form-label"><strong>Имя оператора:</strong></label>
            <input type="text" id="operator_name" name="operator_name" class="form-control" value="{{ shift_assignment.operator.username }}" required>
        </div>

        <div class="mb-3">
            <label for="operation_name" class="form-label"><strong>Название операции:</strong></label>
            <input type="text" id="operation_name" name="operation_name" class="form-control" value="{{ shift_assignment.operation_name }}" required>
        </div>

        <div class="mb-3">
            <label for="machine_id" class="form-label"><strong>Номер станка:</strong></label>
            <input type="text" id="machine_id" name="machine_id" class="form-control" value="{{ shift_assignment.machine_id }}" required>
        </div>

        <div class="mb-3">
            <label for="part_id" class="form-label"><strong>Наименование детали:</strong></label>
            <input type="text" id="part_id" name="part_id" class="form-control" value="{{ shift_assignment.part_id }}" required>
        </div>

        <div class="mb-3">
            <label for="batch_number" class="form-label"><strong>Номер партии:</strong></label>
            <input type="text" id="batch_number" name="batch_number" class="form-control" value="{{ shift_assignment.batch_number }}" required>
        </div>

        <div class="mb-3">
            <label for="quantity" class="form-label"><strong>Количество:</strong></label>
            <input type="number" id="quantity" name="quantity" class="form-control" value="{{ shift_assignment.quantity }}" min="0" required>
        </div>

        <div class="mb-3">
            <label for="defect_quantity" class="form-label"><strong>Количество брака:</strong></label>
            <input type="number" id="defect_quantity" name="defect_quantity" class="form-control" value="0" min="0" required>
        </div>

        <div class="mb-3">
            <label for="stop_reason" class="form-label"><strong>Причины остановки станка:</strong></label>
            <select id="stop_reason" name="stop_reason" class="form-select" required>
                <option value="" disabled selected>Выберите причину</option>
                <option value="Работа в нормальном режиме">Работа в нормальном режиме</option>
                <option value="СлНал">СлНал</option>
                <option value="ТОиР">ТОиР</option>
                <option value="Прочее">Прочее</option>
            </select>
        </div>

        <h2 style="margin-top: 40px">Сохранить Выполненное задание в профиль</h2>

        <!-- Кнопка для отправки формы -->
        <button type="submit" class="btn btn-success">Сохранить</button>
    </form>
</div>

{% endblock %}

<!-- Подключаем CSS файл -->
<link rel='stylesheet' href='{% static 'process_history/css/styles.css' %}' type='text/css'>

<!-- Подключаем JS файл -->
<script src='{% static 'process_history/js/scripts.js' %}'></script>